services:
  # nginx
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  app:
    image: php:8.3-fpm-alpine
    # build:
    #   dockerfile: ./php/Dockerfile
    volumes:
      # - ./app:/app
      # - ./session-01:/app/public
      # - ./session-02:/app/public
      - ./session-03:/app/public
      # - ./session-04:/app/public
      # - ./session-05:/app/public
  # php
  # mysql
  # redis
